name: Build & Publish

on:
  - push

jobs:
  build-publish:
    runs-on: ubuntu-24.04

    concurrency:
      group: ${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.0.0
      - name: Setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
          git update-index --assume-unchanged .npmrc
          pnpm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: pnpm run build
